### ISSUE TITLE
Respond directly from within notification

### ISSUE THREAD

**Issue by jpawlowski** [iAmericanBoy/CountDays#8]
Would be neat if one could 3d touch on a notification and increase the streak right from here!
Not sure but should automatically work on Apple Watch as well. You might know somebody loving that a lot I guess ;-)

**Comment by iAmericanBoy** [comment]
I’m considering doing a simple streak view as the custom notification, so you can see the current streakcount when force pressing the notification.

**Comment by iAmericanBoy** [comment]
let me know what the newest build(Build 42) will show on the watch.

**Comment by jpawlowski** [comment]
I got three options to  choose from and tapped on "OK Continue". Doesn't really fit to the question being asked before but technically it seems that it worked well :-)

**Comment by iAmericanBoy** [comment]
Well the question asked is user generated so my best guess was to answer the default question: Did you continue your daily streak of X. Maybe the button label should be just  “continue” or “continue streak” ?

**Comment by ghost** [comment]
I feel like this is more a yes/no question so "continue" doesn't fit. You tell me :-)
